export const characters = [
  {
    id: "walter",
    number: "01",
    initials: "WW",
    symbol: "W",
    role: "主反应物 · PROTAGONIST",
    name: "沃尔特·怀特",
    englishName: "Walter White / Heisenberg",
    image: "/assets/characters/walter.png",
    imageAlt: "沃尔特·怀特角色宣传照",
    headline: "尊严逐渐变成支配欲",
    description:
      "他以家人的未来为起点，却在一次次“必要选择”中迷恋上不可替代的感觉。海森堡并非面具，而是被压抑人生释放出的真实一面。",
    level: "96%",
    traits: "野心 / 控制 / 精确",
    delay: 0,
  },
  {
    id: "jesse",
    number: "02",
    initials: "JP",
    symbol: "J",
    role: "不稳定剂 · CONSCIENCE",
    name: "杰西·平克曼",
    englishName: "Jesse Pinkman",
    image: "/assets/characters/jesse.png",
    imageAlt: "杰西·平克曼角色宣传照",
    headline: "最混乱的人，守住最多人性",
    description:
      "从不被认可的学生到被操控的合伙人，杰西承担了帝国扩张最直接的情感代价。他的愧疚、善意与求生欲，让故事始终保留人的温度。",
    level: "74%",
    traits: "良知 / 创伤 / 自由",
    delay: 60,
  },
  {
    id: "skyler",
    number: "03",
    initials: "SW",
    symbol: "S",
    role: "抑制剂 · FAMILY",
    name: "斯凯勒·怀特",
    englishName: "Skyler White",
    image: "/assets/characters/skyler.png",
    imageAlt: "斯凯勒·怀特角色宣传照",
    headline: "家庭从庇护所变成封闭容器",
    description:
      "她最早嗅到谎言，也最清楚家庭正在被什么侵蚀。从抵抗到被迫协作，她的选择呈现了亲密关系中的恐惧、责任与困局。",
    level: "67%",
    traits: "警觉 / 保护 / 困守",
    delay: 120,
  },
  {
    id: "hank",
    number: "04",
    initials: "HS",
    symbol: "H",
    role: "检测试剂 · PURSUIT",
    name: "汉克·施拉德",
    englishName: "Hank Schrader",
    image: "/assets/characters/hank.png",
    imageAlt: "汉克·施拉德角色宣传照",
    headline: "猎人离答案越近，家就越危险",
    description:
      "缉毒探员与亲密家人两种身份构成最大的戏剧反差。他从自负、创伤中重建，并凭执拗追踪那位始终坐在餐桌对面的敌人。",
    level: "82%",
    traits: "执着 / 勇气 / 盲点",
    delay: 0,
  },
  {
    id: "gus",
    number: "05",
    initials: "GF",
    symbol: "G",
    role: "稳定剂 · ORDER",
    name: "古斯塔沃·弗林",
    englishName: "Gustavo Fring",
    image: "/assets/characters/gus.png",
    imageAlt: "古斯塔沃·弗林角色剧照",
    headline: "绝对秩序遇上不可控的自尊",
    description:
      "礼貌的餐厅老板与冷静的地下帝王共存于同一张脸。他用耐心、制度和复仇搭建机器，却低估了沃尔特破坏规则的能力。",
    level: "89%",
    traits: "秩序 / 耐心 / 复仇",
    delay: 60,
  },
  {
    id: "saul",
    number: "06",
    initials: "SG",
    symbol: "S",
    role: "催化剂 · FIXER",
    name: "索尔·古德曼",
    englishName: "Saul Goodman",
    image: "/assets/characters/saul.png",
    imageAlt: "索尔·古德曼角色宣传照",
    headline: "只要价格合适，问题总有出口",
    description:
      "他把法律变成犯罪产业的接口，把每次危机包装成一项服务。轻佻幽默背后，是一套让帝国得以快速运转的灰色基础设施。",
    level: "61%",
    traits: "机变 / 交易 / 逃生",
    delay: 120,
  },
];

export const seasons = [
  {
    number: "01",
    short: "点燃",
    roman: "I",
    phase: "IGNITION",
    label: "SEASON 01 · IGNITION",
    title: "点燃：绝境中的第一锅",
    text: "癌症诊断击碎日常，沃尔特找上昔日学生杰西，在新墨西哥荒漠的房车里完成第一次制毒。求生方案很快遭遇现实暴力，也让他第一次发现自己擅长掌控危险。",
    temperature: 24,
  },
  {
    number: "02",
    short: "扩散",
    roman: "II",
    phase: "DIFFUSION",
    label: "SEASON 02 · DIFFUSION",
    title: "扩散：蓝色产品进入城市",
    text: "图科让沃尔特和杰西看见地下市场的暴力规则；索尔与古斯则打开更庞大的产业入口。产品越走越远，谎言与代价也穿过家庭边界，形成一场看不见的连锁反应。",
    temperature: 43,
  },
  {
    number: "03",
    short: "加压",
    roman: "III",
    phase: "PRESSURE",
    label: "SEASON 03 · PRESSURE",
    title: "加压：精密系统里的不稳定变量",
    text: "超级实验室把个人手艺升级为工业生产，也让沃尔特进入古斯的控制体系。替代者、追查者与失控的合伙人同时靠近，密闭容器里的压力迅速越过安全值。",
    temperature: 65,
  },
  {
    number: "04",
    short: "爆炸",
    roman: "IV",
    phase: "DETONATION",
    label: "SEASON 04 · DETONATION",
    title: "爆炸：两位帝王只能留下一个",
    text: "古斯的秩序与沃尔特的自尊展开零和对抗。毒物、怀疑、复仇与亲情都成为棋子。沃尔特不再只是应对威胁，他开始主动设计一场足以重写地下版图的爆炸。",
    temperature: 88,
  },
  {
    number: "05",
    short: "沉降",
    roman: "V",
    phase: "FALLOUT",
    label: "SEASON 05 · FALLOUT",
    title: "沉降：帝国在最高点解体",
    text: "扫清古斯之后，沃尔特建立真正属于自己的帝国。然而一本书把汉克带到答案面前，所有被压缩的因果同时释放。胜利、家庭与身份在荒漠中一起崩塌。",
    temperature: 100,
  },
];

export const events = [
  {
    id: "diagnosis",
    cardClass: "event-card--large",
    photoClass: "diagnosis",
    cardSeason: "S01 · E01",
    cardCode: "ABQ",
    caseNo: "INCIDENT 001",
    season: "SEASON 01 · EPISODE 01",
    code: "CATALYST",
    kicker: "THE CATALYST",
    title: "癌症诊断",
    summary: "所有借口与欲望的第一枚催化剂。",
    text: "五十岁生日后的肺癌诊断，让沃尔特第一次以“时间不够”为理由重新计算人生。他决定用化学天赋留下钱，但这个看似明确的目标，很快与长期被压抑的自尊和野心结合。诊断触发了故事，却无法解释他后来每一次主动升级风险的选择。",
    image: "/assets/events/diagnosis.webp",
    imageAlt: "沃尔特得知癌症诊断后的剧情画面",
    imagePosition: "center 38%",
    impact: 82,
    tags: ["生存", "家庭", "自尊"],
  },
  {
    id: "first-cook",
    cardClass: "",
    photoClass: "first-cook",
    cardSeason: "S01",
    cardCode: "RV",
    caseNo: "INCIDENT 002",
    season: "SEASON 01",
    code: "RV / 01",
    kicker: "THE FIRST REACTION",
    title: "荒漠第一锅",
    summary: "教师与学生成为命运共同体。",
    text: "沃尔特与昔日学生杰西在房车中完成第一次制毒。两人的能力互补：一个提供科学精度，一个了解地下市场；两人的性格却始终彼此冲突。这次合作创造了高纯度产品，也建立了一段由秘密、依赖和操控维系的关系。",
    image: "/assets/events/first-cook.jpg",
    imageAlt: "荒漠中的房车与第一次制毒场景",
    imagePosition: "center 52%",
    impact: 88,
    tags: ["房车", "蓝色产品", "师徒"],
  },
  {
    id: "jane",
    cardClass: "event-card--tall",
    photoClass: "butterfly",
    cardSeason: "S02",
    cardCode: "737",
    caseNo: "INCIDENT 003",
    season: "SEASON 02",
    code: "ABQ / 737",
    kicker: "THE BUTTERFLY EFFECT",
    title: "蝴蝶效应",
    summary: "一次冷眼旁观，在城市上空形成回声。",
    text: "沃尔特在关键时刻选择旁观简的死亡，以重新控制杰西。这个私密决定通过悲痛与失职继续扩散，最终在城市上空形成灾难。事件把全剧的因果观推到前台：没有一个选择真正只影响做出它的人。",
    image: "/assets/events/butterfly.webp",
    imageAlt: "沃尔特仰望空中相撞客机残骸的剧情画面",
    imagePosition: "center 46%",
    impact: 91,
    tags: ["简", "旁观", "连锁后果"],
  },
  {
    id: "superlab",
    cardClass: "",
    photoClass: "superlab",
    cardSeason: "S03",
    cardCode: "LAB",
    caseNo: "INCIDENT 004",
    season: "SEASON 03",
    code: "LAB / 03",
    kicker: "THE SEALED VESSEL",
    title: "超级实验室",
    summary: "手工作坊进入工业时代，也进入牢笼。",
    text: "古斯用工业级实验室、稳定薪酬与专业尊重招募沃尔特。这看似是化学家的理想环境，实则是一套严密的控制系统。当沃尔特意识到自己可以被替换，专业合作迅速转为权力战争，实验室也从成就象征变成封闭牢笼。",
    image: "/assets/events/superlab.webp",
    imageAlt: "沃尔特与杰西站在超级实验室中的剧情画面",
    imagePosition: "center 22%",
    impact: 76,
    tags: ["古斯", "工业化", "控制"],
  },
  {
    id: "gale",
    cardClass: "",
    photoClass: "gale",
    cardSeason: "S03 · FINALE",
    cardCode: "G.B.",
    caseNo: "INCIDENT 005",
    season: "SEASON 03 · FINALE",
    code: "G.B. / 05",
    kicker: "THE POINT OF NO RETURN",
    title: "盖尔门前的枪声",
    summary: "杰西扣下扳机，师徒再也无法回到原点。",
    text: "为了让古斯无法杀死沃尔特，杰西被迫面对盖尔并扣下扳机。这是师徒关系中最残酷的绑定：沃尔特用杰西的良知换取自己的生存。从此，杰西承担的不只是犯罪风险，更是无法轻易摆脱的精神创伤。",
    image: "/assets/events/gale.webp",
    imageAlt: "盖尔在门前面对杰西的剧情画面",
    imagePosition: "center 36%",
    impact: 95,
    tags: ["盖尔", "杰西", "不可逆"],
  },
  {
    id: "faceoff",
    cardClass: "event-card--tall",
    photoClass: "faceoff",
    cardSeason: "S04 · FINALE",
    cardCode: "DING",
    caseNo: "INCIDENT 006",
    season: "SEASON 04 · FINALE",
    code: "DING / 06",
    kicker: "THE DETONATION",
    title: "最后一次按铃",
    summary: "复仇成为引线，护理院成为爆心。",
    text: "沃尔特把赫克托对古斯的仇恨变成引线，在护理院完成致命布局。古斯建立多年的秩序被一次爆炸终结。沃尔特赢下战争，也跨过新的边界：他不再只是逃离死亡，而是在证明自己比对手更会设计死亡。",
    image: "/assets/events/faceoff-b.webp",
    imageAlt: "护理院爆炸后古斯走出房间的剧情画面",
    imagePosition: "center 28%",
    impact: 100,
    tags: ["古斯", "赫克托", "权力真空"],
  },
  {
    id: "hank",
    cardClass: "",
    photoClass: "hank",
    cardSeason: "S05",
    cardCode: "W.W.",
    caseNo: "INCIDENT 007",
    season: "SEASON 05",
    code: "W.W. / 07",
    kicker: "THE DISCOVERY",
    title: "一本书的答案",
    summary: "追查一年的人，原来一直坐在餐桌边。",
    text: "汉克在怀特家中偶然看到盖尔题赠给“W.W.”的书，零散线索突然组成完整图像。最危险的敌人一直是自己的家人。这个发现让追捕从职业任务变成私人背叛，也让沃尔特精心分隔的两个世界正面相撞。",
    image: "/assets/events/hank.webp",
    imageAlt: "汉克翻开写有 W.W. 题赠的《草叶集》",
    imagePosition: "center 48%",
    impact: 97,
    tags: ["汉克", "W.W.", "身份暴露"],
  },
  {
    id: "felina",
    cardClass: "event-card--large",
    photoClass: "finale",
    cardSeason: "S05 · E16",
    cardCode: "FeLiNa",
    caseNo: "INCIDENT 008",
    season: "SEASON 05 · EPISODE 16",
    code: "FeLiNa",
    kicker: "THE FINAL EQUATION",
    title: "回到实验室",
    summary: "承认、清算与最后一次化学反应。",
    text: "流亡后的沃尔特回到阿尔伯克基，安排资金、承认真正动机，并完成最后一次清算。他救出杰西，也让自己的生命终止在最熟悉的实验设备旁。结局没有抹去伤害，只让他终于停止用家庭替自己的欲望命名。",
    image: "/assets/events/finale.webp",
    imageAlt: "终局中沃尔特倒在实验室地面的俯拍画面",
    imagePosition: "center 54%",
    impact: 100,
    tags: ["承认", "清算", "终局"],
  },
];
